/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'
import { Route as PedidoSucessoRouteImport } from './routes/pedido.sucesso'
import { Route as PedidoErroRouteImport } from './routes/pedido.erro'
import { Route as ApiPublicMercadoPagoWebhookRouteImport } from './routes/api/public/mercado-pago-webhook'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProdutosRoute,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProdutosRoute,
} as any)
const PedidoSucessoRoute = PedidoSucessoRouteImport.update({
  id: '/pedido/sucesso',
  path: '/pedido/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoErroRoute = PedidoErroRouteImport.update({
  id: '/pedido/erro',
  path: '/pedido/erro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadoPagoWebhookRoute =
  ApiPublicMercadoPagoWebhookRouteImport.update({
    id: '/api/public/mercado-pago-webhook',
    path: '/api/public/mercado-pago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/criar-conta': typeof CriarContaRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/pedido/erro': typeof PedidoErroRoute
  '/pedido/sucesso': typeof PedidoSucessoRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/api/public/mercado-pago-webhook': typeof ApiPublicMercadoPagoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/criar-conta': typeof CriarContaRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/sobre': typeof SobreRoute
  '/pedido/erro': typeof PedidoErroRoute
  '/pedido/sucesso': typeof PedidoSucessoRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos': typeof ProdutosIndexRoute
  '/api/public/mercado-pago-webhook': typeof ApiPublicMercadoPagoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/criar-conta': typeof CriarContaRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/pedido/erro': typeof PedidoErroRoute
  '/pedido/sucesso': typeof PedidoSucessoRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/api/public/mercado-pago-webhook': typeof ApiPublicMercadoPagoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/carrinho'
    | '/checkout'
    | '/contato'
    | '/criar-conta'
    | '/login'
    | '/minha-conta'
    | '/produtos'
    | '/sobre'
    | '/pedido/erro'
    | '/pedido/sucesso'
    | '/produtos/$slug'
    | '/produtos/'
    | '/api/public/mercado-pago-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blog'
    | '/carrinho'
    | '/checkout'
    | '/contato'
    | '/criar-conta'
    | '/login'
    | '/minha-conta'
    | '/sobre'
    | '/pedido/erro'
    | '/pedido/sucesso'
    | '/produtos/$slug'
    | '/produtos'
    | '/api/public/mercado-pago-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/carrinho'
    | '/checkout'
    | '/contato'
    | '/criar-conta'
    | '/login'
    | '/minha-conta'
    | '/produtos'
    | '/sobre'
    | '/pedido/erro'
    | '/pedido/sucesso'
    | '/produtos/$slug'
    | '/produtos/'
    | '/api/public/mercado-pago-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContatoRoute: typeof ContatoRoute
  CriarContaRoute: typeof CriarContaRoute
  LoginRoute: typeof LoginRoute
  MinhaContaRoute: typeof MinhaContaRoute
  ProdutosRoute: typeof ProdutosRouteWithChildren
  SobreRoute: typeof SobreRoute
  PedidoErroRoute: typeof PedidoErroRoute
  PedidoSucessoRoute: typeof PedidoSucessoRoute
  ApiPublicMercadoPagoWebhookRoute: typeof ApiPublicMercadoPagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/pedido/sucesso': {
      id: '/pedido/sucesso'
      path: '/pedido/sucesso'
      fullPath: '/pedido/sucesso'
      preLoaderRoute: typeof PedidoSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/erro': {
      id: '/pedido/erro'
      path: '/pedido/erro'
      fullPath: '/pedido/erro'
      preLoaderRoute: typeof PedidoErroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercado-pago-webhook': {
      id: '/api/public/mercado-pago-webhook'
      path: '/api/public/mercado-pago-webhook'
      fullPath: '/api/public/mercado-pago-webhook'
      preLoaderRoute: typeof ApiPublicMercadoPagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProdutosRouteChildren {
  ProdutosSlugRoute: typeof ProdutosSlugRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
}

const ProdutosRouteChildren: ProdutosRouteChildren = {
  ProdutosSlugRoute: ProdutosSlugRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
}

const ProdutosRouteWithChildren = ProdutosRoute._addFileChildren(
  ProdutosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  ContatoRoute: ContatoRoute,
  CriarContaRoute: CriarContaRoute,
  LoginRoute: LoginRoute,
  MinhaContaRoute: MinhaContaRoute,
  ProdutosRoute: ProdutosRouteWithChildren,
  SobreRoute: SobreRoute,
  PedidoErroRoute: PedidoErroRoute,
  PedidoSucessoRoute: PedidoSucessoRoute,
  ApiPublicMercadoPagoWebhookRoute: ApiPublicMercadoPagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
